set_property SRC_FILE_INFO {cfile:C:/Pranay/Projects/vivado/Lab10_1/Nexys4DDR_Master.xdc rfile:../../../Nexys4DDR_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clk }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15 	IOSTANDARD LVCMOS33 } [get_ports { multiplicand[0] }]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16 	IOSTANDARD LVCMOS33 } [get_ports { multiplicand[1] }]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M13 	IOSTANDARD LVCMOS33 } [get_ports { multiplicand[2] }]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R15 	IOSTANDARD LVCMOS33 } [get_ports { multiplier[0] }]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R17 	IOSTANDARD LVCMOS33 } [get_ports { multiplier[1] }]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T18 	IOSTANDARD LVCMOS33 } [get_ports { multiplier[2] }]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { rst }]; #IO_L21P_T3_DQS_14 Sch=sw[15]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN H17 	IOSTANDARD LVCMOS33 } [get_ports { product[0] }]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN K15 	IOSTANDARD LVCMOS33 } [get_ports { product[1] }]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN J13 	IOSTANDARD LVCMOS33 } [get_ports { product[2] }]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN N14 	IOSTANDARD LVCMOS33 } [get_ports { product[3] }]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN R18 	IOSTANDARD LVCMOS33 } [get_ports { product[4] }]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict 	{ PACKAGE_PIN V17 	IOSTANDARD LVCMOS33 } [get_ports { product[5] }]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { start }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { done }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
